### ISSUE TITLE
Example server

### ISSUE THREAD

**Issue by gucki** [mdlayher/dhcp6#3]
It would be great to have a basic working dhcp6 server example using this library.

**Comment by mdlayher** [comment]
Hi there!  I have a few that aren't committed, but I could try to clean one up and make it work.  I'll see what I can do in the near future.

**Comment by gucki** [comment]
Hey, thanks that would be really great! :+1:

**Comment by mdlayher** [comment]
Just committed a basic example server!

https://github.com/mdlayher/dhcp6/tree/master/cmd/dhcp6d

There's a lot more to DHCPv6 than what I've done in this basic example.  If you are planning on writing a full-fledged server using this package, please do let me know!  I haven't had the chance to use it in a production environment yet.

Fixed in 8b0169560f19dd3bbb080cddba4fcc52dfae79ab.

**Comment by gucki** [comment]
Hey, thank you for your very fast response! I'll look at in the following few days and let you know how it works. Thanks again!
